version: "3.3"

services:
  wikijs:
    build: 
      context: ./wikijs    
      args:
        ANNOTATE_URL: /viewer/web/viewer.html
    command: yarn start
    environment:
      POSTGRES_HOST: wikijs_db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}    

  wikijs_db:
    image: postgres    
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}     
    restart: always
    volumes:
      - db_data:/var/lib/postgres    

  hypothesis_pdfjs:
    build: ./hypothesis-pdfjs

  hypothesis_client:
    build: 
      context: ./hypothesis-client
      dockerfile: Dockerfile
      args:
        SIDEBAR_APP_URL: ${SIDEBAR_APP_URL}
        CLIENT_ID: ${CLIENT_ID}        

  nginx:
    image: nginx:latest
    depends_on:
      - wikijs
      - hypothesis_client
      - hypothesis_pdfjs
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf              

volumes:
  db_data:                        