version: "3.3"

services:
  wikijs:
    build: 
      context: ./wikijs    
      args:
        ANNOTATE_URL: /viewer/web/viewer.html
    command: yarn dev
    environment:
      ANNOTATE_URL: /viewer/web/viewer.html
      POSTGRES_HOST: wikijs_db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}    
    volumes:
      - ./wikijs/:/usr/src/app/          
      - /usr/src/app/node_modules      

  wikijs_db:
    image: postgres    
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}     
    restart: always
    volumes:
      - db_data:/var/lib/postgres   
       
  nginx:
    image: nginx:latest
    depends_on:
      - wikijs
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.wiki.conf:/etc/nginx/nginx.conf              

volumes:
  db_data:                        